language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0

install:
  - travis_retry composer self-update
  - travis_retry composer update --prefer-dist --no-interaction

script:
  - mkdir -p build/logs
  - protected/vendor/bin/phpcs
  - protected/vendor/bin/phpunit

after_script:
  - protected/vendor/bin/coveralls -v